
#Used primarily for debugging or pack creation. May not be ideal to have turned on when playing the game
["Debug Settings"]
	#Show item tags in the tooltip of an item, when using advanced tooltips (F3 + h).
	show_item_tags = false
	#Play a ding and print a message upon successful reload
	show_reload_message = true
	#How fast a ui should change states each tick (example between two colors)
	#Range: 0.001 ~ 1.0
	ui_interpolation_speed = 0.25

