#Should JSG check for update on startup?
#SIDE: CLIENT
"Check for updates" = true
#SIDE: SERVER/CLIENT
#Range: 0.0 ~ 3.0
"JSG sounds volume" = 1.0
#Specifies transparency of glyphs on notebook page
#SIDE: CLIENT
#Range: 0.0 ~ 1.0
"Notebook page Glyph transparency" = 0.75
#Specifies what unit will be used to display temperatures
#SIDE: CLIENT
#Allowed Values: KELVIN, CELSIUS, FAHRENHEITS
"Temperature unit" = "CELSIUS"
#Disables showing custom main menu
#WARNING! - Requires reloading!
#SIDE: CLIENT
"Disable JSG main menu" = true
#Specifies how many images can be used as background of mainmenu. (starts from 0)
#DO NOT CHANGE THIS IF YOU DO NOT KNOW WHAT ARE YOU DOING!
#WARNING! - Requires reloading!
#SIDE: CLIENT
"Main menu background images count" = 7
#WARNING! - Requires reloading!
#SIDE: CLIENT
"Enable Tau'ri logo on startup" = true
#SIDE: CLIENT
"Enable debug mode in main menu" = false
#SIDE: CLIENT
"Play music in main menu" = true

