#The delay in ticks before the spell is cast
#Range: > 0
delay = 10
#The cost of casting this spell
#Range: > 0
cost = 15
#Base healing amount
#Range: 1 ~ 100
base_heal = 5
#Reputation gained from healing other entities
#Range: 1 ~ 100
rep_from_heal = 3
#Devotion to extra healing ratio
#Range: 0.0 ~ 1.0
devotion_to_heal = 0.05

