
#FollowVoice Config
#Defines how mobs react to player voices, including their movement speed, detection range, and reaction threshold.
[mob_voice_configs]
	mob_configs = ["minecraft:zombie=speed=1.5,range=20,threshold=-40.0", "minecraft:skeleton=speed=1.2,range=15,threshold=-35.0"]

#RunawayVoiceGoal Config
#Defines how animals react to player voices, including their fleeing speed, detection range, and reaction threshold.
[animal_voice_configs]
	animal_configs = ["minecraft:cow=speed=1.5,range=15,threshold=-45.0", "minecraft:pig=speed=1.2,range=5,threshold=-45.0"]

#Whisper Config
#Multipliers that affect the detection range and movement speed when the player is whispering.
[whisper_configs]
	#Range: 0.0 ~ 1.0
	whisper_range_multiplier = 0.5
	#Range: 0.0 ~ 1.0
	whisper_speed_multiplier = 0.8

#Misc Config
#Multipliers that affect the detection range of voices in specific situations.
[misc_config]
	#Range: 0.0 ~ 1.0
	thunder_range_multiplier = 0.5
	#Range: 0.0 ~ 1.0
	sneaking_range_multiplier = 0.5

