
#Generator Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	advancedSolarPanel = "288000"
	#Base energy storage (Joules).
	hybridSolarPanel = "864000"
	#Base energy storage (Joules).
	ultimateHybridSolarPanel = "2592000"
	#Base energy storage (Joules).
	quantumSolarPanel = "7776000"
	#Base energy storage (Joules).
	spectralSolarPanel = "23328000"
	#Base energy storage (Joules).
	singularSolarPanel = "69984000"
	#Base energy storage (Joules).
	lightAbsorbingSolarPanel = "209952000"
	#Base energy storage (Joules).
	photonicSolarPanel = "629856000"
	#Base energy storage (Joules).
	creativeSolarPanel = "2000000000"

