
#MoreSolarPanels Config. This config is synced between server and client.
[solarpanels]
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	advancedSolarPanel = "150"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	hybridSolarPanel = "450"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	ultimateHybridSolarPanel = "1350"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	quantumSolarPanel = "4050"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	spectralSolarPanel = "12150"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	singularSolarPanel = "36450"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	lightAbsorbingSolarPanel = "109350"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	photonicSolarPanel = "328050"
	#Peak output for the Solar Generator. Note: It can go higher than this value in some extreme environments.
	creativeSolarPanel = "10000000"

