
#General mod settings
[general]
	#-
	Storm_NoSnowstorms = false
	#-
	Snowstorm_UseGlobalServerRate = false
	#-
	#Range: > -2147483648
	Snowstorm_OddsTo1 = 30
	#Time between snowstorms for either each player or entire server depending on if global rate is on, default: 3 client days
	#Range: > -2147483648
	Snowstorm_TimeBetweenInTicks = 72000
	#Amount of game ticks between snow buildup iterations, keep it high to prevent client side chunk tick spam that destroys FPS
	#Range: > -2147483648
	Snowstorm_Snow_Buildup_TickRate = 40
	#Base amount of loops done per iteration, scaled by the snowstorms intensity (value given here is the max possible), eg: at max storm intensity, every 40th tick, itll try to build up snow in 800 places around the storm
	#Range: > -2147483648
	Snowstorm_Snow_Buildup_LoopAmountBase = 800
	#Max height of snow allowed to buildup against something, higher = things get more buried over time
	#Range: > -2147483648
	Snowstorm_Snow_Block_Max_Height = 5
	#Allow layered snow blocks to buildup outside cold biomes where snowstorm is
	Snowstorm_Snow_Buildup_AllowOutsideColdBiomes = true

