
[tweaks]

	[tweaks.infinity]
		#Adds a special texture for arrows shot from infinity bows
		"Infinity arrow texture" = true
		#Adds a glint on arrows shot from infinity bows
		"Infinity arrow glint" = true

