#FE stored per byte.
#Range: > 1
amount = 4194304
#The I/O limit of Flux Accessor. 0 means no limitation.
#Range: 0 ~ 2147483647
io_limit = 0
#Allow Flux Accessor to charge ME network with stored FE.
enable = false
#Allow ME Import Bus to pull FE.
enable_FE_pull = false

