
#Config for Warping Spell Prism
[warping_spell_prism]
	#Max Source cost of Warping Spell Prism (1 Source Jar = 10000 Source)
	max_cost = 5000
	#The minimum distance before Warping Spell Prism costs Source
	cost_min_distance = 128
	#Source Cost per block of Warping Spell Prism
	cost_per_block = 1
	#Source Cost when crossing dimensions of Warping Spell Prism
	dimension_cost = 1000

