
["all mobs"]
	"Enable the fix for melee cooldowns for mobs?" = true
	#This determines the range a mob will detect other entities if they have the blindness potion, by default entities will only detect targets in a 10 block radius if they are blinded.
	#Range: -500.0 ~ 10000.0
	"Blindness range" = 0.1
	"Have all mobs attack villagers?" = false
	#Any mob id in this list will not attack villagers if the config option for that is on.
	"Mob BlackList" = []
	"Allow mobs to open fence gates if they are already able to open doors" = true
	#Any mob id input in this list will not open fence gates if they're already able to open doors
	"Fence Gate Opening Blacklist" = ["minecraft:husk", "minecraft:zombie", "minecraft:vindicator", "minecraft:drowned"]
	"Enable new bow ai?" = true
	"Mobs that don't have the new bow ai" = []
	"Enable jumping ai" = true
	"List additional mobs that can also utilize jumping" = ["guardvillagers:guard"]
	"Mobs that don't have the jumping ai" = ["minecraft:villager"]

[husk]
	"Enable burrowing attack for husk?" = true

[pillager]
	"Have pillagers run while reloading?" = true
	"Have pillagers go closer to you if they have a multishot crossbow?" = true
	#Range: 0.0 ~ 900.0
	"Chance of a pillager patrol leader getting a spyglass" = 0.5

[animals]
	"Have animals alert their kin to panic if hurt?" = true
	#Any mob id in this list will attempt to find an area to stay in while it's raining or at night.
	"Animal BlackList" = ["minecraft:cow", "minecraft:pig", "minecraft:sheep", "minecraft:chicken", "minecraft:llama", "minecraft:mooshroom", "minecraft:cat"]
	#Any mob id in this list will not attempt to find an area to stay in while it's night.
	"Animal Night BlackList" = ["minecraft:cat"]
	#Any mob id in this list will not attempt to find an area to stay in while it's raining.
	"Animal Raining BlackList" = []
	"Animals seek shelter?" = true

	[animals.pigs]
		#Range: > -2147483648
		"What is the minimium amount of extra piglets that could be bred?" = 1
		#Range: > -2147483648
		"What is the maxmium amount of extra piglets that could be bred?" = 4

["polar bears"]
	"Have polar bears attack fish?" = true

[ocelots]
	"Have ocelots attack creepers? (Creepers won't attack back)" = true
	"Have ocelots attack parrots?" = true
	"Have ocelots attack phantoms?" = true

[sheep]
	"Have sheep run away from wolves?" = true

["snow golems"]
	#Freezing time can be added up by successive shots.
	"Allow snow balls to apply 5 seconds of freezing when they hit an entity?" = true

