#Boat Overhaul Client Config
#Allows a boat to turn its rudder with a very small extra forward speed when the gear state is at STOP
allowRudderingWhenStopped = false
#If set to true, a boat sailing backwards and ruddering to right, for example, will sail to the left rearward
reverseRudderWhenSailingAstern = false
#X offset of gear indicator
#Range: -10000 ~ 10000
gearX = 0
#Y offset of gear indicator
#Range: -10000 ~ 10000
gearY = 0
#X offset of rudder indicator
#Range: -10000 ~ 10000
rudderX = 0
#Y offset of rudder indicator
#Range: -10000 ~ 10000
rudderY = 0

