
[general]

	[general.general]
		#Always create full creative-mode chests when formed. Should not be used in survival worlds!
		creativeChests = false
		#If the interface input overlay should always be rendered on chests.
		alwaysShowInterfaceOverlay = true
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorDiamond = 4.0
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorObsidian = 4.0
		#If items should be ejected from the chests if one of the structure blocks are removed.
		ejectItemsOnDestroy = false
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorIron = 2.0
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorWood = 1.0
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorCopper = 1.666
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorGold = 3.0
		#If the higher tier metal variants (including diamond and obsidian) can be crafted.
		metalVariants = true
		#Multiplier for the number of inventory slots for this chest material.
		chestInventoryMaterialFactorSilver = 2.666

	[general.colossal_chest]
		#If the chest should visually open when someone uses it.
		chestAnimation = true

[core]

	[core.general]
		#If mod compatibility loader should crash hard if errors occur in that process.
		crashOnModCompatCrash = false
		#Maximum buffer byte size for adaptive inventory slots fragmentation.
		maxPacketBufferSize = 20000
		#If the recipe loader should crash when finding invalid recipes.
		crashOnInvalidRecipe = false
		#If an anonymous mod startup analytics request may be sent to our analytics service.
		analytics = true
		#If the version checker should be enabled.
		versionChecker = true

[machine]

	[machine.colossal_chest]
		#The maximum size a colossal chest can have.
		maxSize = 20

