
#general settings
[general]
	#Blacklisted Items - add the name of the item to blacklist, modid:item_name format, separated with comma.
	#Example: "curios:amulet", "curios:ring".
	forbiddenTrinkets = []

