
#Settings for the mechanical spawner
[mechanical_spawner]
	#Stress impact
	#Range: 0.0 ~ 1.7976931348623157E308
	stressImpact = 16.0
	#Minimum required speed
	#Range: 0.0 ~ 1.7976931348623157E308
	minimumSpeed = 100.0
	#Liquid capacity
	#Range: > 1
	liquidCapacity = 1000
	#Max range
	#Range: 1 ~ 6
	maxRange = 2
	#Allow Create Item Vault as loot collector
	allowAnyContainerLootCollector = false
	#Forces to require a loot collector for the spawner to work.
	lootCollectorRequired = false
	#Loot collector capacity in stacks
	#Range: 1 ~ 16
	lootCollectorCapacity = 8
	#Enables alternative loot for spawner recipes.
	customLootPerSpawnRecipeEnabled = true

