
#.
#Modify Create Encased blocks comportements
[kinetics]
	#.
	#.
	#Can swap casing between block (Mixer, Press, Depot, Gearbox, etc...)
	casingBlockSwappable = true
	#.
	#Can swap material between shafts,cogwheels and large cogwheels (includes brass,andesite and glass)
	shaftCogwheelsSwappable = true
	#.
	#Should Brass/Copper/Train mixe faster
	shouldCustomMixerMixeFaster = true
	#.
	#Should Wooden Shaft break if the speed is too high
	shouldWoodenShaftBreak = true
	#.
	#Should Glass Shaft break if the system is overstressed
	shouldGlassShaftBreak = true
	#.
	#The max speed wooden shafts can endure
	#Range: 2 ~ 256
	maxSpeedWoodenShaft = 32

