
#Settings for the mechanical sifter
[sifter]
	#Stress impact
	#Range: 0.0 ~ 64.0
	stressImpact = 4.0
	#Minimum required speed
	#Range: 0.0 ~ 254.0
	minimumSpeed = 1.0
	#Output item capacity
	#Range: > 1
	outputCapacity = 16

#Settings for the mechanical brass sifter
[brass_sifter]
	#Stress impact
	#Range: 0.0 ~ 64.0
	stressImpact = 8.0
	#Minimum required speed
	#Range: 0.0 ~ 254.0
	minimumSpeed = 16.0
	#Items processed per cycle
	#Range: 1 ~ 64
	outputCapacity = 8

