
#---------------------------------------|| Entity settings ||---------------------------------------
[entity_properties]

	[entity_properties.silkmoth]
		#The probability to spawn a Silkmoth on a Mulberry each random tick is equal to 1/x, with x the following value :
		#Range: 10 ~ 10000
		silkmothSpawnChance = 400
		#Range: 0 ~ 10
		silkmothRotationMaxRange = 2
		silkmothDiesAfterOneDay = true
		#The probability to change the rotation point each tick is equal to 1/x, with x the following value :
		#Range: 10 ~ 10000
		silkmothRotationChange = 400
		silkmothMute = false

	[entity_properties.japanese_dragon]
		#Range: 1 ~ 10000
		japaneseDragonDefaultMaxHealth = 60
		#Range: 1 ~ 100
		japaneseDragonDefaultAttack = 4
		japaneseDragonMute = false

#---------------------------------------|| Block settings ||----------------------------------------
[block_properties]

	[block_properties.dryer]
		#The drying time of an item is randomly set in an interval around the default time from the recipe. The following value defines the high bound of the interval in percents. IE, if you choose '20', the interval will be [ 83.3% , 120%]. If you chose '200', the interval will be [33.3% , 300%] :
		#Range: 0 ~ 100000
		dryingTimeVariationRange = 30

	[block_properties.climbing_plant]
		#The probability to grow is equal to 1/x, with x the following value :
		#Range: 1 ~ 200
		climbingPlantGrowthChance = 16
		#If the plant could have grown (see climbingPlantGrowthChance), it has a probability to spread to an adjacent block equal to 1/x, with x the following value :
		#Range: 1 ~ 1000
		climbingPlantSpreadChance = 5

	[block_properties.stick_bundle]
		#Worms have a probability to grow on random tick equal to 1/x, with x the following value :
		#Range: 1 ~ 1000
		stickBundleGrowthChance = 25

