
[Rendering]
	#Always Enables the halloween Slider
	"Always Enable Halloween Slider" = false
	#Never Enables the halloween Slider, not even during halloween
	"Never Enable Halloween Slider" = false
	#Changes to some Deep Aether's old mob model such as the Eye of The Storm
	"Switches To Legacy Mob Models" = false

