
["Client Settings"]
	#Setting this to false will disable camera shakes.
	cameraShakesAllowed = true
	#Setting this to false will disable the webbed screen overlay
	#Requires game restart
	webbedScreen = true
	#Setting this to false will disable the jumpscare after killing ragno
	#Requires game restart
	doJumpscare = true
	#Setting this to true will turn on Arachnophobe-Safe Mode, Ragno will become a horrifying monstrosity in a different way
	arachnophobeMode = false

