
["Integrated Villages"]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	["Integrated Villages".General]
		# Whether or not vanilla villages should be disabled.
		# Default: true
		#
		"Disable Vanilla Villages" = true
		# Whether or not create contraptions such as windmills will be activated on world generation. Turning this to false could prevent some lag.
		# Default: true
		#
		"Activate Create Contraptions" = true

