
["Mob Settings"]

	["Mob Settings"."Chorusling Settings"]
		#Multiplies damage dealt by Chorusling
		#Range: 0.0 ~ 100.0
		"Chorusling Damage Multiplier" = 1.0
		#Multiplies health of Chorusling
		#Range: 0.0 ~ 100.0
		"Chorusling Health Multiplier" = 1.0

	["Mob Settings"."Endersent Settings"]
		#Multiplies damage dealt by Endersent
		#Range: 0.0 ~ 100.0
		"Endersent Damage Multiplier" = 1.0
		#Multiplies health of Endersent
		#Range: 0.0 ~ 100.0
		"Endersent Health Multiplier" = 1.0

	["Mob Settings"."Spiky Worm Settings"]
		#Multiplies damage dealt by Spiky Worm
		#Range: 0.0 ~ 100.0
		"Spiky Worm Damage Multiplier" = 1.0
		#Multiplies health of Spiky Worm
		#Range: 0.0 ~ 100.0
		"Spiky Worm Health Multiplier" = 1.0

	["Mob Settings"."Ambusher Settings"]
		#Multiplies damage dealt by Ambusher
		#Range: 0.0 ~ 100.0
		"Ambusher Damage Multiplier" = 1.0
		#Multiplies health of Ambusher
		#Range: 0.0 ~ 100.0
		"Ambusher Health Multiplier" = 1.0
		#Enables Projectile Damage For Ambusher
		"Allow Ambusher Projectile Damage" = true

	["Mob Settings"."Ancient Guardian Settings"]
		#Multiplies damage dealt by Ancient Guardian
		#Range: 0.0 ~ 100.0
		"Ancient Guardian Damage Multiplier" = 1.0
		#Multiplies health of Ancient Guardian
		#Range: 0.0 ~ 100.0
		"Ancient Guardian Health Multiplier" = 1.0
		#Enables/Disables Stun Ability for Ancient Guardian. §cNOTE: Disabling This may make the bossfight less fun.
		"Allow Ancient Guardian Stun Ability" = true
		#Enables Projectile Damage for Ancient Guardian
		"Allow Ancient Guardian Projectile Damage" = true

	["Mob Settings"."Haunted Knight Settings"]
		#Multiplies damage dealt by Haunted Knight
		#Range: 0.0 ~ 100.0
		"Haunted Knight Damage Multiplier" = 1.0
		#Multiplies health of Haunted Knight
		#Range: 0.0 ~ 100.0
		"Haunted Knight Health Multiplier" = 1.0
		#Enables Projectile Damage For Haunted Knight
		"Allow Haunted Knight Projectile Damage" = true

	["Mob Settings"."Haunted Guard Settings"]
		#Multiplies damage dealt by Haunted Guard
		#Range: 0.0 ~ 100.0
		"Haunted Guard Damage Multiplier" = 1.0
		#Multiplies health of Haunted Guard
		#Range: 0.0 ~ 100.0
		"Haunted Guard Health Multiplier" = 1.0
		#Enables Projectile Damage For Haunted Guard
		"Allow Haunted Guard Projectile Damage" = true

	["Mob Settings"."Posessed Paladin Settings"]
		#Multiplies damage dealt by Posessed Paladin
		#Range: 0.0 ~ 100.0
		"Posessed Paladin Damage Multiplier" = 1.0
		#Multiplies health of Posessed Paladin. §cNOTE: Disabling This may make the bossfight less fun.
		#Range: 0.0 ~ 100.0
		"Posessed Paladin Health Multiplier" = 1.0
		#Enables/Disables Stun Ability for Posessed Paladin
		"Allow Posessed Paladin Stun Ability" = true
		#Enables Projectile Damage Posessed Paladin
		"Allow Posessed Paladin Projectile Damage" = true

	["Mob Settings"."Overgrown Colosuss Settings"]
		#Multiplies damage dealt by Overgrown Colosuss
		#Range: 0.0 ~ 100.0
		"Overgrown Colosuss Damage Multiplier" = 1.0
		#Multiplies health of Overgrown Colosuss
		#Range: 0.0 ~ 100.0
		"Overgrown Colosuss Health Multiplier" = 1.0
		#Enables/Disables Stun Ability for Overgrown Colosuss. §cNOTE: Disabling This may make the bossfight less fun.
		"Allow Overgrown Colosuss Stun Ability" = true
		#Enables Projectile Damage for Overgrown Colosuss
		"Allow Overgrown Colosuss Projectile Damage" = true

	["Mob Settings"."Mossy Golem Settings"]
		#Multiplies damage dealt by Mossy Golem
		#Range: 0.0 ~ 100.0
		"Mossy Golem Damage Multiplier" = 1.0
		#Multiplies health of Mossy Golem
		#Range: 0.0 ~ 100.0
		"Mossy Golem Health Multiplier" = 1.0
		#Enables Projectile Damage for Dune Sentinel
		"Allow Dune Sentinel Projectile Damage" = true

	["Mob Settings"."Cloud Golem Settings"]
		#Multiplies damage dealt by Cloud Golem
		#Range: 0.0 ~ 100.0
		"Cloud Golem Damage Multiplier" = 1.0
		#Multiplies health of Cloud Golem
		#Range: 0.0 ~ 100.0
		"Cloud Golem Health Multiplier" = 1.0
		#Enables Projectile Damage for Cloud Golem
		"Allow Cloud Golem Projectile Damage" = true

	["Mob Settings"."Cloud Golem's Falling Cloud Settings"]
		#Multiplies damage dealt by Falling Cloud
		#Range: 0.0 ~ 100.0
		"Falling Cloud Damage Multiplier" = 1.0

	["Mob Settings"."Frostbitten Golem Settings"]
		#Multiplies damage dealt by Frostbitten Golem
		#Range: 0.0 ~ 100.0
		"Frostbitten Golem Damage Multiplier" = 1.0
		#Multiplies health of Frostbitten Golem
		#Range: 0.0 ~ 100.0
		"Frostbitten Golem Health Multiplier" = 1.0
		#Enables Projectile Damage for Frostbitten Golem
		"Allow Frostbitten Golem Projectile Damage" = true

	["Mob Settings"."Dune Sentinel Settings"]
		#Multiplies damage dealt by Dune Sentinel
		#Range: 0.0 ~ 100.0
		"Dune Sentinel Damage Multiplier" = 1.0
		#Multiplies health of Dune Sentinel
		#Range: 0.0 ~ 100.0
		"Dune Sentinel Health Multiplier" = 1.0
		#Multiplies damage dealt by Bomber
		#Range: 0.0 ~ 100.0
		"Bomber Damage Multiplier" = 1.0
		#Multiplies health of Bomber
		#Range: 0.0 ~ 100.0
		"Bomber Health Multiplier" = 1.0

	["Mob Settings"."Skeletosaurus Settings"]
		#Multiplies damage dealt by Skeletosaurus
		#Range: 0.0 ~ 100.0
		"Skeletosaurus Damage Multiplier" = 1.0
		#Multiplies health of Skeletosaurus
		#Range: 0.0 ~ 100.0
		"Skeletosaurus Health Multiplier" = 1.0

	["Mob Settings"."Lava Eater Settings"]
		#Multiplies damage dealt by Lava Eater
		#Range: 0.0 ~ 100.0
		"Lava Eater Damage Multiplier" = 1.0
		#Multiplies health of Lava Eater
		#Range: 0.0 ~ 100.0
		"Lava Eater Health Multiplier" = 1.0
		#Enables Projectile Damage for Lava Eater
		"Allow Lava Eater Projectile Damage" = true

	["Mob Settings"."Warped Fungussus Settings"]
		#Multiplies damage dealt by Warped Fungussus
		#Range: 0.0 ~ 100.0
		"Warped Fungussus Damage Multiplier" = 1.0
		#Multiplies health of Warped Fungussus
		#Range: 0.0 ~ 100.0
		"Warped Fungussus Health Multiplier" = 1.0

	["Mob Settings"."Withered Abomination Settings"]
		#Multiplies damage dealt by Withered Abomination
		#Range: 0.0 ~ 100.0
		"Withered Abomination Damage Multiplier" = 1.0
		#Multiplies health of Withered Abomination
		#Range: 0.0 ~ 100.0
		"Withered Abomination Health Multiplier" = 1.0
		#Enables/Disables Stun Ability for Withered Abomination
		"Allow Withered Abomination Stun Ability" = false

	["Mob Settings"."Shulker Mimic Settings"]
		#Multiplies damage dealt by Shulker Mimic
		#Range: 0.0 ~ 100.0
		"Shulker Mimic Damage Multiplier" = 1.0
		#Multiplies health of Shulker Mimic
		#Range: 0.0 ~ 100.0
		"Shulker Mimic Health Multiplier" = 1.0
		#Enables Projectile Damage for Shulker Mimic
		"Allow Shulker Mimic Projectile Damage" = true

