
[spirit]
	#If set to true, any spirits dropped will simply take the form of an item.
	noFancySpirits = false
	#If set to true, any spirits dropped through non-entity-means will simply take the form of an item.
	noFancySpiritsTotem = true

	[spirit.spawner]
		#If set to true, mob spawners will create soulless mobs instead.
		lameSpawners = false

	[spirit.defaults]
		#Whether entities without spirit jsons will use the default spirit data for their category.
		defaultSpiritValues = true

	[spirit.affinity]

		[spirit.affinity.soul_ward]
			#Multiplier for physical damage taken while soul ward is active.
			#Range: 0.0 ~ 1.0
			soulWardPhysical = 0.699999988079071
			#Multiplier for magic damage taken while soul ward is active.
			#Range: 0.0 ~ 1.0
			soulWardMagic = 0.10000000149011612
			#Base time in ticks it takes for one point of soul ward to recover.
			soulWardRate = 100

[compat]

	[compat.irons_spellbooks]
		#Should Iron's Spellbooks' magic damage count as Soul Damage?
		ironsSpellbooksPlayerSpiritDrops = true
		#Should Iron's Spellbooks' magic damage when dealt by non-players count as Soul Damage
		ironsSpellbooksNonPlayerSpiritDrops = true

[codex]
	#If set to true, the first undead enemy a player slays will drop the encyclopedia arcana.
	enableCodexDrop = true

