
#Settings for all burners' parameters
[parameters]
	#The minimum heat value required to become seething. (super heating)
	seething_heat = 340.0
	#The minimum heat value required to become kindled. (heating)
	kindled_heat = 200.0
	#The minimum heat value required to become fading. (heating)
	fading_heat = 160.0
	#The minimum heat value required to become smouldering.
	smouldering_heat = 80.0

	#Settings for ember burner's parameters
	[parameters.ember_burner]
		#The max amount of ember capacity.
		max_capacity = 6000.0
		#The amount of ember consumed per tick.
		ember_cost = 1.0
		#The amount of heat gained per second when consuming ember.
		heating_rate = 1.0
		#The amount of heat lost per second when not consuming ember.
		cooling_rate = 1.0
		#The value to multiply on the heating rate and the cooling rate when ember burner is adjacent to atmospheric bellows.
		rate_multiplier = 2.0
		#The maximum heat value the ember burner can reach without atmospheric bellows.
		max_heat = 300.0
		#The maximum heat value the ember burner adjacent to atmospheric bellows can reach.
		max_heat_1 = 400.0
		#The maximum heat value the ember burner one blocks away from atmospheric bellows can reach.
		max_heat_2 = 340.0

	#Settings for heat converter's parameters
	[parameters.heat_converter]
		#The minimum temperature required to become seething. (super heating)
		seething_temp = 1200.0
		#The minimum temperature required to become kindled. (heating)
		kindled_temp = 450.0
		#The minimum temperature required to become fading. (heating)
		fading_temp = 400.0
		#The minimum temperature required to become smouldering.
		smouldering_temp = 200.0
		#The amount of temperature decreased per tick.
		temp_cost = 2.0

	#Settings for exoflame compat parameters
	[parameters.exoflame_compat]
		#Maximum number of blaze burner exoflame can provide heat sustainably.
		boost_rate = 9
		#Maximum number of blaze burner exoflame can provide heat sustainably when superheated.
		seething_boost_rate = 1

	#Settings for electric burner's parameters
	[parameters.electric_burner]
		#The max amount of energy capacity.
		max_capacity = 50000
		#The amount of energy consumed per tick.
		energy_cost = 100
		#The value to multiply on the energy consumed per tick when heating.
		energy_multiplier_1 = 1.5
		#The value to multiply on the energy consumed per tick when super heating.
		energy_multiplier_2 = 2.0
		#The amount of heat gained per second when consuming energy.
		heating_rate = 1.0
		#The amount of heat lost per second when not consuming energy.
		cooling_rate = 1.0
		#The maximum heat value the electric burner can reach before upgraded.
		max_heat = 300.0
		#The maximum heat value the electric burner can reach after upgraded.
		upgraded_max_heat = 400.0

