
#To configure the dimension and dimension type please create a data pack and add a dimension type in this resource location: data/overworldmirror/dimension_type/overworld_mirror.json and a dimension in this resource location: data/overworldmirror/dimension/overworld.json
[information]
	information = ""

#Portal settings
[portal]
	#How many blocks the portal can be from the normal spawn location to not create a new one.
	#Range: 1.0 ~ 1.0E10
	portalSearchDistanceOverworld = 30.0
	#How many blocks the portal can be from the normal spawn location to not create a new one.
	#Range: 1.0 ~ 1.0E10
	portalSearchDistanceOverworldMirror = 30.0

