
#General configuration options
[General]
	#The harvest level names used by the Tool Info Tweak tooltips.
	harvestLevelNames = ["Stone", "Iron", "Diamond", "Obsidian", "Netherite"]

#Disable features.
[Features]
	#Tool Information Tooltips enabled?
	toolInfoTooltip = true

