# This config file is for getting default values, for use in propertymodifier-common.toml. It is NOT directly usable!
# Due to internal reasons, stripping, flattening, tilling and entity modifiers cannot be extracted.
