#How much time in ticks should the virtual sacrificer wait before producing blood [100]
#Range: > 1
sacrificer_speed = 100
#The energy capacity of the virtual sacrificer [1000000]
#Range: > 1
sacrificer_energy = 1000000
#How much data to give to the model each iteration [1]
#Set to 0 to disable
#Range: > 0
sacrificer_data = 1
#Should data be given to faulty models? [true]
faulty_data = true

