
["Core Upgrade Table"]
	driving_core_2_material2_consume = 4.0
	driving_core_2_materia3_consume = 2.0
	driving_core_2_kills = 0.0
	driving_core_3_materia2_consume = 8.0
	driving_core_3_materia3_consume = 4.0
	driving_core_3_kills = 10.0
	driving_core_4_materia2_consume = 12.0
	driving_core_4_material3_consume = 6.0
	driving_core_4_kills = 8.0
	acid_core_2_material2_consume = 32.0
	acid_core_2_material3_consume = 12.0
	acid_core_2_kills = 8.0
	acid_core_3_material2_consume = 64.0
	acid_core_3_material3_consume = 12.0
	acid_core_3_kills = 10.0
	nether_core_2_material2_consume = 12.0
	nether_core_2_material3_consume = 32.0
	nether_core_2_kills = 4.0
	nether_core_3_material2_consume = 12.0
	nether_core_3_material3_consume = 48.0
	nether_core_3_kills = 6.0
	nether_core_4_material2_consume = 12.0
	nether_core_4_material3_consume = 64.0
	nether_core_4_kills = 10.0
	driving_core_2_material2 = "minecraft:iron_ingot"
	driving_core_2_material3 = "silence_s_defense_tower:pile_of_materials_1"
	driving_core_3_material2 = "minecraft:iron_ingot"
	driving_core_3_material3 = "silence_s_defense_tower:pile_of_materials_1"
	driving_core_4_material2 = "minecraft:iron_ingot"
	driving_core_4_material3 = "silence_s_defense_tower:pile_of_materials_1"
	acid_core_2_material2 = "minecraft:copper_ingot"
	acid_core_2_material3 = "minecraft:slime_ball"
	acid_core_3_material2 = "minecraft:copper_ingot"
	acid_core_3_material3 = "minecraft:slime_ball"
	nether_core_2_material2 = "minecraft:gold_ingot"
	nether_core_2_material3 = "silence_s_defense_tower:nether_wart_sauce"
	nether_core_3_material2 = "minecraft:gold_ingot"
	nether_core_3_material3 = "silence_s_defense_tower:nether_wart_sauce"
	nether_core_4_material2 = "minecraft:gold_ingot"
	nether_core_4_material3 = "silence_s_defense_tower:nether_wart_sauce"

["Vending Machine"]
	diamond = 6.0
	gold_ingot = 2.0
	props = 1.0
	technology_small = 1.0
	technology_large = 4.0
	add_item1 = ""
	add_item1_consume = 0.0
	add_item1_output = 0.0
	add_item2 = ""
	add_item2_consume = 0.0
	add_item2_output = 0.0
	add_item3 = ""
	add_item3_consume = 0.0
	add_item3_output = 0.0
	add_item4 = ""
	add_item4_consume = 0.0
	add_item4_output = 0.0
	biological_jamming_device_ban = false

[Turret]
	cannon_1_damage = 4.0
	cannon_1_attackrange = 16.0
	cannon_2_damage = 7.0
	cannon_2_attackrange = 16.0
	ice_cannon_1_damage = 5.0
	ice_cannon_1_attackrange = 16.0
	arrow_turret_1_damage = 2.0
	arrow_turret_1_attackrange = 18.0
	arrow_turret_2_damage = 3.0
	arrow_turret_2_attackrange = 18.0
	heavy_crossbow_1_damage = 35.0
	heavy_crossbow_1_attackrange = 22.0
	dart_launcher_1_damage = 1.5
	dart_launcher_1_attackrange = 15.0
	dart_launcher_2_damage = 2.0
	dart_launcher_2_attackrange = 15.0
	sentry_gun_1_damage1 = 4.0
	sentry_gun_1_damage2 = 2.0
	sentry_gun_1_attackrange = 17.0
	submarine_1_damage = 6.0
	submarine_1_attackrange = 18.0
	candy_turret_1_damage1 = 7.0
	candy_turret_1_damage2 = 2.5
	candy_turret_1_attackrange = 17.0
	candy_turret_2_damage1 = 11.0
	candy_turret_2_damage2 = 4.0
	candy_turret_2_attackrange = 17.0
	giant_dart_launcher_1_damage = 2.0
	giant_dart_launcher_1_dattackrange = 16.0
	giant_dart_launcher_2_damage2 = 1.5
	giant_dart_launcher_2_dattackrange = 18.0
	firework_launcher_1_damage = 3.0
	firework_launcher_1_attackrange = 18.0
	firework_launcher_2_damage = 4.0
	miniature_electromagnetic_gun_1_damage = 3.6
	miniature_electromagnetic_gun_1_attackrange = 18.0
	ball_lightning_gennerator_1_damage = 5.5
	ball_lightning_gennerator_1_attackrange = 18.0
	electromagnetic_gun_1_damage = 12.0
	electromagnetic_gun_1_attackrange = 18.0
	electromagnetic_railgun_1_damage = 28.0
	electromagnetic_railgun_1_attackrange = 30.0
	black_hole_generator_1_damage = 3.0
	black_hole_generator_1_attackrange = 18.0
	acid_eater_1_attackrange = 16.0
	acid_eater_2_attackrange = 17.0
	acid_eater_3_attackrange = 18.0
	acid_arrow_turret_1_damage = 1.5
	acid_arrow_turret_1_attackrange = 18.0
	acid_arrow_turret_2_damage = 3.0
	acid_arrow_turret_2_attackrange = 18.0
	hellraiser_1_damage = 3.0
	hellraiser_1_maxdamage = 15.0
	hellraiser_1_attackrange = 16.0
	hellraiser_2_damage = 4.0
	hellraiser_2_maxdamage = 20.0
	hellraiser_2_attackrange = 17.0
	hellraiser_3_damage = 5.0
	hellraiser_3_maxdamage = 28.0
	hellraiser_3_attackrange = 18.0
	hellraiser_4_damage = 8.0
	hellraiser_4_maxdamage = 32.0
	hellraiser_4_attackrange = 18.0
	"sticky_bomb_battery_damage(×5)" = 3.0
	sticky_bomb_battery_attackrange = 22.0
	amethyst_cannon_damage = 1.0
	amethyst_cannon_attackrange = 18.0
	"amethyst_extra_health(×4)" = 0.0
	tyrant_cannon_remote_damage = 9.0
	tyrant_cannon_melee_leech = 5.0
	tyrant_cannon_1_melee_damage = 12.0
	tyrant_cannon_1_attackrange = 16.0
	tyrant_cannon_2_melee_damage = 15.0
	tesla_electric_tower_damage = 1.5
	tesla_electric_tower_attackrange = 8.0
	biological_jamming_device_attackrange = 15.0
	tyrant_cannon_2_attackrange = 16.0
	robot_barracks_a_damage = 2.0
	robot_barracks_a_attackrange = 12.0
	robot_barracks_a_range = 15.0
	robot_barracks_s_damage = 3.0
	robot_barracks_s_attackrange = 10.0
	robot_barracks_s_range = 15.0
	robot_barracks_c_attackrange = 12.0
	robot_barracks_c_range = 15.0
	healing_pylon_1_heal = 12.0
	healing_pylon_1_attackrange = 15.0
	healing_pylon_2_heal = 20.0
	healing_pylon_2_attackrange = 15.0
	healing_pylon_3_heal = 20.0
	healing_pylon_3_attackrange = 15.0
	hurricane_ballista_1_damage = 3.0
	hurricane_ballista_1_attackrange = 20.0
	hurricane_ballista_2_damage = 4.5
	hurricane_ballista_2_attackrange = 24.0
	miniature_electromagnetic_gun_2_damage = 3.6
	miniature_electromagnetic_gun_2_attackrange = 20.0

["Variety Store"]
	nether_wart_sauce_consume1 = 16.0
	nether_wart_sauce_consume2 = 24.0
	nether_wart_sauce_consume3 = 36.0
	nether_wart_sauce_consume4 = 48.0

["Maintenance Station"]
	driving_core_restoration = "iron_ingot"
	driving_core_restoration_value = 8.0
	nether_core_restoration = "gold_ingot"
	nether_core_restoration_value = 10.0
	acid_core_restoration = "copper_ingot"
	acid_core_restoration_value = 3.0

["Research Table"]
	research_1_item1 = "minecraft:flint"
	research_1_item1_consume = 4.0
	research_1_item2 = "minecraft:iron_ingot"
	research_1_item2_consume = 4.0
	research_1_kills = 8.0
	research_1_time = 60.0
	research_1_output = 4.0
	research_2_item1 = "silence_s_defense_tower:precision_components_2"
	research_2_item1_consume = 1.0
	research_2_item2 = "minecraft:iron_ingot"
	research_2_item2_consume = 4.0
	research_2_kills = 8.0
	research_2_time = 60.0
	research_2_output = 4.0
	research_3_item1 = "silence_s_defense_tower:soul"
	research_3_item1_consume = 1.0
	research_3_item2 = "minecraft:gold_ingot"
	research_3_item2_consume = 2.0
	research_3_kills = 10.0
	research_3_time = 120.0
	research_3_output = 4.0
	research_4_item1 = "silence_s_defense_tower:pile_of_materials_1"
	research_4_item1_consume = 3.0
	research_4_item2 = ""
	research_4_item2_consume = 0.0
	research_4_kills = 8.0
	research_4_time = 120.0
	research_4_output = 4.0
	research_5_consume = 1.0
	research_5_output = 1.0

[Laborartory]
	laborartory_1_material2 = "silence_s_defense_tower:reinforcement_materials_1"
	laborartory_1_material2_consume = 10.0
	laborartory_1_material3 = ""
	laborartory_1_material3_consume = 0.0
	laborartory_2_material2 = "silence_s_defense_tower:reinforcement_materials_2"
	laborartory_2_material2_consume = 1.0
	laborartory_2_material3 = "silence_s_defense_tower:driving_core_3"
	laborartory_2_material3_consume = 1.0
	laborartory_3_material2 = "silence_s_defense_tower:reinforcement_materials_1"
	laborartory_3_material2_consume = 6.0
	laborartory_3_material3 = "minecraft:diamond"
	laborartory_3_material3_consume = 2.0
	laborartory_4_material2 = "silence_s_defense_tower:reinforcement_materials_1"
	laborartory_4_material2_consume = 12.0
	laborartory_4_material3 = "silence_s_defense_tower:electric_arc_1"
	laborartory_4_material3_consume = 3.0
	laborartory_5_material2 = "silence_s_defense_tower:reinforcement_materials_1"
	laborartory_5_material2_consume = 12.0
	laborartory_5_material3 = "silence_s_defense_tower:rubber_band_1"
	laborartory_5_material3_consume = 3.0
	laborartory_6_material2 = "silence_s_defense_tower:reinforcement_materials_2"
	laborartory_6_material2_consume = 2.0
	laborartory_6_material3 = ""
	laborartory_6_material3_consume = 0.0
	laborartory_7_material2 = "minecraft:mutton"
	laborartory_7_material2_consume = 36.0
	laborartory_7_material3 = "silence_s_defense_tower:soul"
	laborartory_7_material3_consume = 3.0
	laborartory_8_material2 = "minecraft:coal"
	laborartory_8_material2_consume = 64.0
	laborartory_8_material3 = "silence_s_defense_tower:soul"
	laborartory_8_material3_consume = 3.0
	laborartory_9_material2 = "minecraft:amethyst_shard"
	laborartory_9_material2_consume = 18.0
	laborartory_9_material3 = "silence_s_defense_tower:soul"
	laborartory_9_material3_consume = 3.0
	laborartory_10_material3 = "silence_s_defense_tower:precision_components_2"
	laborartory_10_material3_consume = 2.0
	laborartory_11_material3 = "silence_s_defense_tower:soul"
	laborartory_11_material3_consume = 2.0

[gamerules]
	#original value(0~999%),maximum value(0~999%)
	technology_damage = 100180.0
	#original value(0~999%),maximum value(0~999%)
	technology_speed = 100160.0
	#maximum value(0~99),original value(0~99)
	technology_health = 2000.0
	#maximum value(0~999%),original value(0~999%)
	technology_heal = 200000.0
	hostile_firework_launcher = true
	#The chance of a reward being dropped when an enemy is killed by a turret(%)
	drop_rewards = 20.0

