
#Simple Sponge Config
[sponge]
	#Set the range for a Sponge
	#Range: 1 ~ 64
	spongeRange = 3
	#Set the range for a Sponge On A Stick
	#Range: 1 ~ 64
	spongeOnAStickRange = 3

[magmatic_sponge]
	#Set the range for a Magmatic Sponge
	#Range: 1 ~ 64
	magmaticSpongeRange = 5
	#Set the range for a Magmatic Sponge On A Stick
	#Range: 1 ~ 64
	magmaticSpongeOnAStickRange = 5

[energized_sponge]
	#Set to true to enable the Energized Sponge On A Stick
	enableEnergizedSpongeOnAStick = true
	#Set the max energy for an Energized Sponge On A Stick
	#Range: > 1
	energizedSpongeOnAStickMaxEnergy = 500000
	#Set the per right click energy use for an Energized Sponge On A Stick
	#Range: > 1
	energizedSpongeOnAStickPerRightClickUse = 1000
	#Set the range for an Energized Sponge On A Stick
	#Range: 1 ~ 64
	energizedSpongeOnAStickRange = 7

[compressed_sponge]
	#Set the range (multiplied by 2) for a Compressed Sponge On A Stick
	#Range: 1 ~ 64
	compressedSpongeOnAStickRange = 3
	#Set the range (multiplied by 2) for a Compressed Magmatic Sponge On A Stick
	#Range: 1 ~ 64
	compressedMagmaticSpongeOnAStickRange = 5

[creative_sponge]
	#Set the range for a Creative Sponge
	#Range: 1 ~ 64
	creativeSpongeRange = 12
	#Set the range for a Creative Sponge On A Stick
	#Range: 1 ~ 64
	creativeSpongeOnAStickRange = 12
	#Set the range (multiplied by 2) for a Compressed Creative Sponge On A Stick
	#Range: 1 ~ 64
	compressedCreativeSpongeOnAStickRange = 12

[misc]
	#By default, regular (non-magmatic) Sponges and Sponge On A Sticks can absorb hot liquid (e.g. Lava) once then breaks.
	#Set this to false if you don't want regular Sponges and Sponge On A Sticks to absorb hot liquid at all.
	regularSpongeAbsorbHotLiquid = true
	#When OpenBlocks is detected, certain crafting recipes will be changed / disabled.
	#Set this to false if you wish to use the Sponges from this mod.
	#You'll have to use CraftTweaker to prevent recipe conflicts.
	openBlocksIntegration = true

