# Whether to enable Soul Fire Aspect enchantment.
# Takes precedence over all other Soul Fire Aspect configs.
"enable soul fire aspect" = true
# Whether Soul Fire Aspect cannot appear in the enchanting table.
# If enabled along with [enable soul fire aspect discovery], the enchantment won't appear in the enchanting table, but can still be found in loots.
"enable soul fire aspect treasure" = false
# Whether Soul Fire Aspect can appear in the enchanting table and loots.
# [enable Soul Fire Aspect treasure] takes precedence.
"enable Soul Fire Aspect discovery" = true
# Whether Soul Fire Aspect can be found in villager trades.
"enable Soul Fire Aspect trades" = true
# Whether to enable Soul Flame enchantment.
# Takes precedence over all other Soul Flame configs.
"enable soul flame" = true
# Whether Soul Flame cannot appear in the enchanting table.
# If enabled along with [enable soul flame discovery], the enchantment won't appear in the enchanting table, but can still be found in loots.
"enable soul flame treasure" = false
# Whether Soul Flame can appear in the enchanting table and loots.
# [enable Soul Flame treasure] takes precedence.
"enable Soul Flame discovery" = true
# Whether Soul Flame can be found in villager trades.
"enable Soul Flame trades" = true

