
[general]
	#Requires game restart! Set to true to remove the uncraftable tooltips for any uncraftable weapon (highlighted in red). Useful for modpack makers who wish to change recipes.
	force_disable_uncraftable_tooltips = false

[integration]
	#Set to true to fully disable integration with Shoulder Surfing Reloaded
	disable_shoulder_surfing_integration = false

[hud]
	#Set to true to disable a new Crosshair for the Crossbow which visually shows inaccuracy, using the default Crosshair instead; false otherwise
	disable_new_crosshairs_crossbow = false
	#Set to true to disable a new Crosshair for Throwing Weapons which show the charge for them, using the default Crosshair instead; false otherwise
	disable_new_crosshairs_throwing_weapons = false
	#Set to force compatibility crosshairs for Crosshairs and Throwing Weapons. This won't work if the new crosshairs are disabled
	force_compatibility_crosshairs = false

	[hud.quiver]
		#Sets where the Quiver HUD Element should be aligned
		#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, CENTER_LEFT, CENTER, CENTER_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
		quiver_hud_alignment = "BOTTOM_CENTER"
		#Sets where on the X-axis the Quiver HUD element should be off-set from it's alignment point
		#Range: -400 ~ 400
		quiver_hud_offset_x = -138
		#Sets where on the Y-axis the Quiver HUD element should be off-set from it's alignment point
		#Range: -400 ~ 400
		quiver_hud_offset_y = 65

	[hud.oil_uses]
		#Sets where the Oil Uses HUD Element should be aligned
		#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, CENTER_LEFT, CENTER, CENTER_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
		oil_uses_alignment = "CENTER"
		#Sets where on the X-axis the Oil Uses HUD element should be off-set from it's alignment point
		#Range: -400 ~ 400
		oil_uses_hud_offset_x = 0
		#Sets where on the Y-axis the Oil Uses HUD element should be off-set from it's alignment point
		#Range: -400 ~ 400
		oil_uses_hud_offset_y = 0

