#Render an indicator similar to the attack indicator while parrying is active.
render_parry_indicator = true
#Use the much simpler third-person pose when blocking with a sword from Minecaft 1.8 instead of the default one from before that.
simple_blocking_pose = false
#Allows block hitting to render properly (meaning attacking and then using the item directly afterwards). The hitting animation is no longer consumed as in vanilla.
full_interact_animations = true

