
[rendering]
	#Toggle control name rendering
	control_name_rendering = true
	#Play idle console animations
	console_idle_animations = true
	#Skip Vortex rendering
	render_vortex_in_door = true
	#Use Custom Internal Shaders
	use_internal_shaders = true

