#When enabled shows the overlay after using a weapon ability (Default: true)
#Reload Resourcepacks after turning this on (F3+T)
DashOverlay = true
#(Y) Coordinate for Misc UI
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
MiscY = 5
#(X) Coordinate for Misc UI
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
MiscX = 4
#(Y) Coordinate for Magma Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
MagmaBarY = 5
#(X) Coordinate for Magma Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
MagmaBarX = 4
#Type of Magma Bar
#Can be edited in-game without reloading packs (If nothing changed reload packs with [F3+T] keybind)
#Range: 1 ~ 3
MagmaBarType = 1
#Item activation on ability use
PhantomActivation = true
#Changes goblin model to old one
#Reload Resourcepacks after turning this on (F3+T)
OldGoblinModel = false
#Bossbar boss titles
BossbarTitles = true
#Custom bossbars
CustomBossbars = true

