#Prevent standing on bedrock at low Y levels from teleporting you to the void from these dimensions
#Example: minecraft:overworld
#
bedrockTeleportationDimensionBlacklist = []
#Changes the bedrock teleportation dimension blacklist config to be a whitelist instead
bedrockTeleportationDimensionWhitelist = false

